export type AiProviderState =
  | "not-configured"
  | "cloud"
  | "heuristic-fallback"
  | "error";

export interface AiSession {
  provider: string;
  state: AiProviderState;
  apiKey: string;
  endpoint: string;
}

export function createSession(provider: string, apiKey: string, endpoint: string): AiSession {
  return {
    provider,
    apiKey,
    endpoint,
    state: apiKey ? "cloud" : "not-configured",
  };
}

export function clearSession(session: AiSession): AiSession {
  return { ...session, apiKey: "", state: "not-configured" };
}

export function describeState(state: AiProviderState): string {
  switch (state) {
    case "cloud":
      return "Cloud provider configured. Requests are sent to the configured provider. No data is sent without an explicit request.";
    case "heuristic-fallback":
      return "Local heuristic fallback. Output is generated by rule-based string inspection, not a model. Do not trust it as verified code.";
    case "error":
      return "The last request failed. No output was produced.";
    case "not-configured":
    default:
      return "No AI provider configured. Set a provider and key to enable cloud assistance, or use the local heuristic fallback.";
  }
}

export function heuristicAssist(prompt: string): string {
  if (!prompt.trim()) return "No prompt provided.";
  const lower = prompt.toLowerCase();
  if (lower.includes("kotlin") || lower.includes("compose")) {
    return [
      "// heuristic-fallback: not a model output",
      "// Suggested Compose scaffold (unverified):",
      "@Composable",
      "fun MyScreen() {",
      "  Column(Modifier.padding(16.dp)) {",
      "    Text(\"Hello\")",
      "  }",
      "}",
    ].join("\n");
  }
  if (lower.includes("gradle")) {
    return [
      "// heuristic-fallback: not a model output",
      "// Common Gradle Kotlin DSL snippet (unverified):",
      "dependencies {",
      "  implementation(\"androidx.compose.ui:ui\")",
      "}",
    ].join("\n");
  }
  return [
    "// heuristic-fallback: not a model output",
    "// I cannot generate a specific answer without a configured provider.",
    "// Please configure a cloud provider or refine the prompt.",
  ].join("\n");
}
